[[plugins]] # あいまい検索
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]] # 曖昧検索
repo = 'junegunn/fzf.vim'

[[plugins]] # ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]] # ディレクトリツリーを表示
repo = 'preservim/nerdtree'

[[plugins]] # git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # quickrun
repo = 'thinca/vim-quickrun'

[[plugins]] # nerdtree に git のマークを出す
repo = 'Xuyuanp/nerdtree-git-plugin'


[[plugins]] # 検索
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]] # git で差分がある行を表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # カラースキーム
repo = 'cocopon/iceberg.vim'

[[plugins]] # 検索件数を表示
repo = 'osyo-manga/vim-anzu'

[[plugins]] # 行番号を指定してファイルを開く
repo = 'bogado/file-line'

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]] # コマンドを置き換える
repo = 'tyru/vim-altercmd'

[[plugins]] # denite の依存プラグイン
repo = 'roxma/nvim-yarp'

[[plugins]] # denite の依存プラグイン
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]] # 対話的なインターフェースを提供
# pip3 install --user pynvim が必要
repo = 'Shougo/denite.nvim'

[[plugins]] # コード補完
repo = 'Shougo/deoplete.nvim'

[[plugins]] # endwise
repo = 'tpope/vim-endwise'

[[plugins]] # インデントを表示
repo = 'Yggdroot/indentLine'

[[plugins]] # open github
repo = 'tyru/open-browser.vim'

[[plugins]] # open github
repo = 'tyru/open-browser-github.vim'

[[plugins]] # binary
repo = 'Shougo/vinarise.vim'

[[plugins]] # operator-replace の依存プラグイン
repo = 'kana/vim-operator-user'

[[plugins]] # オペレータ拡張
repo = 'kana/vim-operator-replace'

[[plugins]] # undoを辿れるようにする
repo = 'mbbill/undotree'

[[plugins]] # vim-textobj-ruby の依存プラグイン
repo = 'kana/vim-textobj-user'

[[plugins]] # rubyのtextobjを扱う
repo = 'rhysd/vim-textobj-ruby'

[[plugins]] # ハイライト
repo = 'sheerun/vim-polyglot'

[[plugins]] # カラースキーマを入れる
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]] # アスタリスクで単語下を検索
repo = 'haya14busa/vim-asterisk'

[[plugins]] # QuickRun setting
repo = 'osyo-manga/denite-quickrun_config'

[[plugins]] # sqlUtilities
repo = 'vim-scripts/Align'

[[plugins]] # sql
repo = 'vim-scripts/SQLUtilities'

[[plugins]] #rails
repo = 'tpope/vim-rails'

[[plugins]] # Scrapbox tool が依存している
repo = 'vim-jp/vital.vim'

[[plugins]] # Filetype=Scrapbox
repo = 'syusui-s/scrapbox-vim'

[[plugins]] # カラースキーマ
repo = 'ghifarit53/tokyonight-vim'
