# --*--*--
# Vim
# --*--*--
[[plugins]] # ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

# --*--*--
# 見た目
# --*--*--
[[plugins]] # カラースキーマ
repo = 'cocopon/iceberg.vim'

[[plugins]] # カラースキーマ
repo = 'ghifarit53/tokyonight-vim'

[[plugins]] # ステータスバー
repo = 'itchyny/lightline.vim'

[[plugins]] # インデントを表示
repo = 'Yggdroot/indentLine'

[[plugins]] # 選択した文字をハイライト
repo = 't9md/vim-quickhl'

[[plugins]] # 行末の空白を可視化
repo = 'ntpeters/vim-better-whitespace'

[[plugins]] # Ansi Escape を色付きで表示
repo = 'powerman/vim-plugin-AnsiEsc'

[[plugins]] # ハイライト
repo = 'osyo-manga/vim-operator-highlighter'

[[plugins]]
repo = 'thinca/vim-operator-sequence'

# --*--*--
# シンタックスハイライト
# --*--*--
[[plugins]] # toml
repo = 'cespare/vim-toml'

[[plugins]] # Vue.js
repo = 'leafOfTree/vim-vue-plugin'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# --*--*--
# Vim拡張
# --*--*--
[[plugins]] # undoを辿れるようにする
repo = 'mbbill/undotree'

[[plugins]] # buffer 同士の比較を簡単にする
repo = 'deris/vim-diffbuf'

[[plugins]] # 行番号を指定してファイルを開く
repo = 'bogado/file-line'

[[plugins]] # QuickFixで置換
repo = 'thinca/vim-qfreplace'

# --*--*--
# 入力補助
# --*--*--
[[plugins]] # endwise
repo = 'tpope/vim-endwise'

[[plugins]] # operator-replace の依存プラグイン
repo = 'kana/vim-operator-user'

[[plugins]] # オペレータ拡張
repo = 'kana/vim-operator-replace'

[[plugins]] # vim-textobj-ruby の依存プラグイン
repo = 'kana/vim-textobj-user'

[[plugins]] # rubyのtextobjを扱う
repo = 'rhysd/vim-textobj-ruby'

[[plugins]] # `sil`
repo = 'kana/vim-textobj-line'

[[plugins]] # なんでもコメントアウト
repo = 'tyru/caw.vim'

[[plugins]] # かっこ自動挿入
repo = 'cohama/lexima.vim'

[[plugins]] # end に対応するやつをハイライト
repo = 'andymass/vim-matchup'

[[plugins]] # operator 実行時にカーソルを移動させない
repo = 'osyo-manga/vim-operator-stay-cursor'

[[plugins]] # text object の囲み文字
repo = 'rhysd/vim-operator-surround'

# --*--*--
# ファイラ
# --*--*--
[[plugins]] # denite の依存プラグイン. Vim 用
repo = 'roxma/nvim-yarp'

[[plugins]] # denite の依存プラグイン. Vim 用
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]] # 対話的なインターフェースを提供
# Vim では pip3 install --user pynvim が必要
repo = 'Shougo/denite.nvim'

[[plugins]] # ファイラ
repo = 'Shougo/defx.nvim'

[[plugins]] # defxにgit差分を表示
repo = 'kristijanhusak/defx-git'

[[plugins]] # defxアイコン
repo = 'ryanoasis/vim-devicons'

[[plugins]] # defxアイコン
repo = 'kristijanhusak/defx-icons'

# --*--*--
# 検索
# --*--*--
[[plugins]] # 検索
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]] # アスタリスクで単語下を検索
repo = 'haya14busa/vim-asterisk'

[[plugins]] # 検索件数を表示
repo = 'osyo-manga/vim-anzu'

[[plugins]] # リファレンスをみるためのツール
repo = 'thinca/vim-ref'

# --*--*--
# QuickRun
# --*--*--
[[plugins]] # quickrun
repo = 'thinca/vim-quickrun'

[[plugins]] # QuickRun setting
repo = 'osyo-manga/denite-quickrun_config'

[[plugins]] # quickrun job
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]] # QuickRunの設定共通
repo = 'osyo-manga/shabadou.vim'

# --*--*--
# LSP
# --*--*--
[[plugins]] # LSP
repo = 'neoclide/coc.nvim'

# --*--*--
# SQL
# --*--*--
[[plugins]] # sqlUtilities
repo = 'vim-scripts/Align'

[[plugins]] # sql
repo = 'vim-scripts/SQLUtilities'

# --*--*--
# Git
# --*--*--
[[plugins]] # git操作
repo = 'tpope/vim-fugitive'

[[plugins]] # git で差分がある行を表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # fugitive の :GBrowse が依存
repo = 'tpope/vim-rhubarb'

# --*--*--
# Scrapbox
# --*--*--
[[plugins]] # Scrapbox tool が依存している
repo = 'vim-jp/vital.vim'

[[plugins]] # Filetype=Scrapbox
repo = 'syusui-s/scrapbox-vim'

# --*--*--
# Browser
# --*--*--
[[plugins]] # ghosttext
repo = 'subnut/nvim-ghost.nvim'

[[plugins]] # rurema等の依存プラグイン
repo = 'tyru/open-browser.vim'
